search_full_content: false
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
twitter_username: null
future: true
collections_dir: content
include:
  - content
search: true
search_provider: lunr
author:
  name: MAKE Roanoke
logo: /assets/images/WhiteMakeRoanokeShadow.png
paginate_path: /page:num/
sass:
  sass_dir: _sass
lang: en-US
markdown: kramdown
url: https://makeroanoke.org
remote_theme: MAKEroanoke/jekyll-theme-basically-make-roanoke
algolia:
  ? application_id
  ? index_name
  ? search_only_api_key
  ? powered_by
github_username: null
defaults:
  - values:
      mermaid: false
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      read_time: true
header_pages:
  - about.markdown
show_excerpts: true
collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title
  events:
    output: true
    permalink: /event/:year/:month/:day/:title
paginate: 10
title: MAKE Roanoke
timezone: America/New_York
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs
  - /example
description: A maker initiative in Roanoke, Virginia.
email: info@makeroanoke.org
baseurl: null
feed:
  path: atom.xml
