# config.yml

local_backend: true

backend:
  branch: main # optional, defaults to master
  base_url: https://sveltia-cms-auth.makeroa.workers.dev/
  name: github # remote name
  repo:  MAKEroanoke/makeroanoke.org
publish_mode: simple #editorial_workflow # in local use simple
media_folder: 'site/assets/images'
public_folder: '/assets/images'
collections:
  - name: 'posts'
    label: 'Posts and Events'
    folder: 'site/content/_posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    sortable_fields: ['date', 'title', 'author' ]
    view_filters:
      - label: "Posts"
        field: categories
        pattern: 'Posts'
      - label: "Events"
        field: categories
        pattern: 'Events'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime', hint: "Publish date if it's a post, the event date if it's en event." }
      - { label: 'Categories', name: 'categories', widget: 'list', hint: "Use Events for classes and events, use Posts for everything else." , required: true, default: 'Post'}
      - { label: 'Tags', name: 'tags', widget: 'list', required: false, hint: "Use for shop names and event types."}
      - { label: 'Excerpt', name: 'excerpt', required: false, widget: 'text', hint: "Summary of the post to be shown on the homepage instead of showing the start of the post."}
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Hero Image', name: 'image', required: false, widget: 'image' }
      - { label: 'Feed Image', name: 'thumbnail', required: false, widget: 'image' }
      - { label: 'Event Location', name: 'location', required: false, widget: 'string', default: "128 Albemarle Ave SE, Roanoke, VA 24013" }
      - { label: 'Permalink', name: 'permalink', widget: 'string', required: false, hint: "Do not edit the permalink unless you know what you are doing."}
      - { label: 'Published', name: 'published', widget: 'boolean', default: 'true', hint: "Hide posts instead of deleting them with this setting." }

  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        editor:
          preview: true
        file: "site/index.html"
        fields:
          - { label: "Title", name: "alt_title", widget: "string" }
          - { label: "Subtitle", name: "sub_title", widget: "string" }
          - { label: "Banner", name: "image", widget: "image" }
          - { label: 'Intro', name: 'introduction', widget: 'markdown' }
      - name: "about"
        label: "About Page"
        editor:
          preview: true
        file: "site/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - name: "makerspace"
        label: "Makerspace"
        editor:
          preview: true
        file: "site/makerspace.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - name: "newsletter"
        label: "Newsletter"
        editor:
          preview: true
        file: "site/newsletter.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: 'Body', name: 'body', widget: 'markdown', hint: "{% include newsletter.html %} adds the newsletter signup form." }
      - name: "events"
        label: "Events"
        editor:
          preview: true
        file: "site/events.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Category Name', name: 'taxonomy', widget: 'string', required: true, default: 'Event', hint: 'Show posts form this category, when then layout is changed to "category".'}
          - { label: 'Page Layout', name: 'layout', widget: 'string', required: true, default: 'page', hint: 'Set this to "page" to show only the content. Set it to "category" to display all posts form the specified category.'}
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "config"
        label: "Website Settings"
        editor:
          preview: false
        file: "site/_config.yml"
        fields:
        - { label: "Title", name: "title", widget: "string", hint: "HTML page title." }
        - { label: "Description", name: "description", widget: "string", hint: "This is added to the page title." }
        - { label: "Email", name: "email", widget: "string", hint: "Used fro the email link in the menu." }
        - { label: "Logo", name: "logo", widget: "image", hint: "Page logo, top left." }
      - name: "theme"
        label: "Theme Settings"
        editor:
          preview: false
        file: "site/_data/theme.yml"
        fields:
        - { label: "Navigation", name: "navigation_pages", widget: "list", hint: "List of filenames of the pages to show in the hamburger menu separated by a comma and space." }
        - { label: "Show Posts on Homepage", name: "posts_on_home_page", widget: "boolean", hint: "Turn the posts on the homepage on and off. The post pages will still exist, but will not be listed on the homepage" }
        - label: 'Theme Settings'
          name: 't'
          widget: object
          fields:
          - { label: "Homepage Posts Section Title", name: "posts", widget: "string", hint: "Title of the section that lists all posts and events." }
