#!/bin/sh
#_path=${1:-$PWD}
_path=$(pwd)
if [ $# -gt 0 ]; then
    _path=$_path/$1
    shift 1
fi

# or run: `docker compose --env-file .jekyll.env up` to change the ports
_command="bundle exec jekyll serve --force_polling -H 0.0.0.0 -P 4000 --livereload"
_image=bretfisher/jekyll-serve:alpine
docker run -it --rm \
       -p 4000:4000 -p 35729:35729 \
       -v "$_path:/site" $_image \
       $_command $@
